#Contacts-Api Stackfile
version: "3.5"
services:
  ui:
    image: devopsbyexample/contacts-api
    ports:
      - "8080:80"
    environment:
      API_HOST: api
      API_PORT: 3000
    deploy:
      labels:
        #com.docker.ucp.access.label: "path"
        com.docker.lb.hosts: master01
        com.docker.lb.network: postgres_password
        com.docker.lb.port: 8080
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2048M

