version: "3"

services:
  webapi:
    image: sixeyed/password-web:v1
    ports:
      - "81:80"
    environment:
      - PasswordApi:Url=http://password-api:5001
  password-api:
    image: sixeyed/password-api:v1
