version: "3"

services:
  webapi:
    image: sixeyed/password-web:v1
    ports:
      - "81:80"
    environment:
      - PasswordApi:Url=http://password-api:5001
    deploy:
      replicas: 5
  password-api:
    image: sixeyed/password-api:v2
    deploy:
      replicas: 10
