version: "3.5"

services:
  webapi:
    image: sixeyed/password-web:v1
    ports:
      - "81:80"
    environment:
      - PasswordApi:Url=http://password-api:5001
    deploy:
      replicas: 2
  password-api:
    image: sixeyed/password-api:v1
    deploy:
      replicas: 3
