# Use postgres/example user/password credentials
version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: contacts
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      development:
        aliases:
          - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2048M
secrets:
  postgres_password:
    external: true
    name: dev_env_appdb01

networks:
  development:
    external: true



