#Contacts-Ui Stackfile
version: '3.5'
services:
  ui:
    image: devopsbyexample/contacts-ui
    ports:
      - "8080:80"
    environment:
      API_HOST: api
      API_PORT: 3000
    networks:
      development:
        aliases:
          - ui
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2048M
networks:
  development:
    external: true
