#Contacts-Api Stackfile
version: "3.5"
services:
  api:
    image: devopsbyexample/contacts-api
    environment:
      DB_HOSTNAME: db
      DB_NAME: contacts
      DB_USERNAME: test
      DB_PASSWORD: test
    secrets:
      - db_password
    configs:
      - source: dev_config_app01
        target: /var/dev_config_app01.conf
    networks:
      development:
        aliases:
          - api
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '1'
          memory: 2048M
secrets:
  db_password:
    external: true
    name: dev_env_appdb01

networks:
  development:
    external: true

configs:
  dev_config_app01:
      external: true


